name: GitHub Snake Game (Dark Mode)

on:
  # Schedule the workflow to run daily at midnight UTC
  schedule:
    - cron: "0 0 * * *"
  # Allow manual triggering of the workflow
  workflow_dispatch:
  # Trigger the workflow on pushes to the main branch
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Generate the dark mode snake animation
      - name: Generate GitHub Contributions Snake Animations (Dark Mode)
        uses: Platane/snk@v3
        with:
          # Your GitHub username
          github_user_name: NaazShayema
          # Define the output files for dark mode
          outputs: |
            dist/github-snake-dark.svg?palette=github-dark
            dist/dark-ocean.gif?color_snake=#ffcc00&color_dots=#1e293b,#334155,#475569,#64748b,#94a3b8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Deploy the generated files to the 'output' branch
      - name: Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          # Custom commit message
          commit_message: "Update dark mode snake animation [skip ci]"



